Only include schemaType and References when needed
riferrei/srclient pull request #98
Opened 2023-01-24 20:07 UTC by adamtabrams

Older versions of the Confluent Schema Registry API don't support fields `schemaType` or `References`. Right now, this package always includes these in requests, even if they aren't being used. Since these fields were added to the API, the documentation has stated that they are optional fields. And it's documented that `schemaType` is always assumed to be Avro when it isn't specified. 

This PR ensures that these fields are only included in the request when they're not empty. And it does this with minimal changes to the package.

This PR would fix issues that I've faced in my own use case and handles cases mentioned in previous issues:
https://github.com/riferrei/srclient/issues/11 https://github.com/riferrei/srclient/issues/19 https://github.com/riferrei/srclient/issues/21

In addition to the unit tests added in this PR, I've also tested these changes with integration tests specific to my use case.

Please feel free to mention any questions or concerns.

2023-03-10 19:44 UTC, adamtabrams commented
Just bumping this PR
@riferrei @AtakanColak

2023-03-15 18:05 UTC, AtakanColak requested changes

2023-03-15 18:06 UTC, AtakanColak commented
Hi Adam, thank you for your contribution. I'm inclined to merge this change, except the part I've commented on. Could you please either walk me through the cases where empty schema type would be required or revert the change?

2023-03-15 18:55 UTC, adamtabrams commented on schemaRegistryClient.go
> +		return ""
This method is only called when setting the `SchemaType` field for a `schemaRequest` struct. The [Confluent Schema Registry docs](https://docs.confluent.io/platform/current/schema-registry/develop/api.html) state that `AVRO` is the default `schemaType`.

When you're creating a `schemaRequest` and it's `SchemaType` is `AVRO`, you want `SchemaType` to be set to `""`. This causes the `schemaType` field to be omitted from the json.

This code works together with the `omitempty` tag to get the desired behavior. If `SchemaType` is set to `"AVRO"`, then `schemaType` will be included in the json and older versions of Schema Registry won't be compatible.

2023-03-15 20:07 UTC, adamtabrams commented on schemaRegistryClient.go
> +		return ""
I added one

2023-03-16 10:51 UTC, merged

2023-03-16 10:51 UTC, AtakanColak commented
Thanks 👍